-- 테이블 삭제
drop table COMMENTS
CASCADE CONSTRAINTS;

--시퀀스 삭제
DROP SEQUENCE MAIN_PDS_COMMENT_SEQ;

--테이블 생성
CREATE TABLE COMMENTS(
	POST_SEQ NUMBER NOT NULL,
	COMMENT_GROUP_NO NUMBER NOT NULL,
	COMMENT_SHAPE VARCHAR2(10) DEFAULT '0' NOT NULL,
	COMMENT_SEQ NUMBER PRIMARY KEY,
	COMMENT_STATUS NUMBER DEFAULT 1 NOT NULL,
	USER_ID VARCHAR2(50) NOT NULL,
	COMMENT_CONTENT VARCHAR2(50) NOT NULL,
	COMMENT_CREATE_AT DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_COMMENTS_BBS_SEQ FOREIGN KEY(POST_SEQ)
	REFERENCES POSTS(POST_SEQ) ON DELETE CASCADE,
	CONSTRAINT FK_COMMENTS_USER_ID FOREIGN KEY(USER_ID)
	REFERENCES USERS(USER_ID) ON DELETE CASCADE	
);

--외래키
ALTER TABLE COMMENTS
ADD CONSTRAINT FK_COMMENTS_ID FOREIGN KEY(USER_ID)
REFERENCES USERS(USER_ID);

--시퀀스 생성
CREATE SEQUENCE COMMENTS_SEQ
START WITH 1 INCREMENT BY 1;

--조회
SELECT * FROM COMMENTS;

SELECT 
	BBS_SEQ as bbsSeq, 
	COMMENT_GROUP_NO as commentGroupNo,
	COMMENT_SHAPE as commentShape,
	COMMENT_SEQ as commentSeq,
	COMMENT_STATUS as commentStatus,
	USER_ID as userId, 
	COMMENT_CONTENT as commentContent, 
	COMMENT_CREATE_AT as commentCreateAt
FROM (
		SELECT BBS_SEQ,COMMENT_GROUP_NO,COMMENT_SHAPE,COMMENT_SEQ,COMMENT_STATUS,USER_ID,COMMENT_CONTENT,COMMENT_CREATE_AT,
			ROW_NUMBER() OVER (ORDER BY COMMENT_GROUP_NO DESC, COMMENT_SHAPE DESC) R
		FROM COMMENTS
		WHERE BBS_SEQ = 91
		AND COMMENT_STATUS = 1
)
WHERE R BETWEEN 0 and 10

--삭제
DELETE FROM COMMENTS;

--수정
UPDATE COMMENTS
SET COMMENT_STATUS = 1
WHERE COMMENT_SEQ = 1

--데이터 삽입
INSERT INTO COMMENTS(
	BBS_SEQ,COMMENT_GROUP_NO,COMMENT_SEQ,USER_ID,COMMENT_CONTENT
)
VALUES(
	21, COMMENTS_SEQ.NEXTVAL, COMMENTS_SEQ.NEXTVAL, '20170010', '안녕하세요'
)