
DELETE FROM ADMIN;
DELETE FROM ASSESSMENT;
DELETE FROM COMMENTS;
DELETE FROM ECLASS_COMMENTS;
DELETE FROM ECLASS_NOTICE_BBS;
DELETE FROM ECLASS_PDS_BBS;
DELETE FROM INTRO_BBS;
DELETE FROM MAIN_BBS;
DELETE FROM MAIN_PDS_COMMENT;
DELETE FROM PDS;
DELETE FROM POLL;
DELETE FROM PROFESSOR;
DELETE FROM STUDENT;
DELETE FROM SUBJECT;
DELETE FROM USERS;
DELETE FROM VOTER;
