SELECT *
FROM USER_SEQUENCES;

DROP SEQUENCE MAIN_BBS_SEQ;
DROP SEQUENCE ECLASS_PDS_BBS_SEQ;
DROP SEQUENCE ECLASS_NOTICE_BBS_SEQ;
DROP SEQUENCE COMMENTS_SEQ;

DROP TABLE ADMIN
CASCADE CONSTRAINT;

DROP TABLE PROFESSOR
CASCADE CONSTRAINT;

DROP TABLE STUDENT
CASCADE CONSTRAINT;

DROP TABLE SUBJECT
CASCADE CONSTRAINT;

DROP TABLE USERS
CASCADE CONSTRAINT;

DROP TABLE ASSESSMENT
CASCADE CONSTRAINT;

DROP TABLE COMMENTS
CASCADE CONSTRAINT;

DROP TABLE MAIN_BBS
CASCADE CONSTRAINT;

DROP TABLE ECLASS_NOTICE_BBS
CASCADE CONSTRAINT;

DROP TABLE ECLASS_PDS_BBS
CASCADE CONSTRAINT;

DROP TABLE MAIN_PDS_COMMENT
CASCADE CONSTRAINT;
