--테이블 삭제
DROP TABLE POSTS
CASCADE CONSTRAINT;

DROP SEQUENCE POSTS_SEQ;

--테이블 생성
CREATE TABLE POSTS(
	BOARD_SEQ NUMBER NOT NULL,
    REF NUMBER(8) NOT NULL,
    REPLY VARCHAR2(10) DEFAULT '0' NOT NULL,
    POST_SEQ NUMBER(8) PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT VARCHAR2(4000) NOT NULL,
    READCOUNT NUMBER(8) DEFAULT 0 NOT NULL,
    STORED_FILENAME VARCHAR2(200) DEFAULT '-1' NOT NULL,
    ORG_FILENAME VARCHAR2(200) DEFAULT '-1' NOT NULL,
    STATUS VARCHAR2(10) DEFAULT '공개' NOT NULL,
    WDATE DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT FK_BOARD_SEQ FOREIGN KEY(BOARD_SEQ)
	REFERENCES BOARDS(BOARD_SEQ) ON DELETE CASCADE,
	CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID)
	REFERENCES USERS(USER_ID) ON DELETE CASCADE
);

--외래키 생성
ALTER TABLE MAIN_BBS
ADD CONSTRAINT FK_MAIN_BBS_ID FOREIGN KEY(USER_ID)
REFERENCES USERS(USER_ID);

--시퀀스 생성
CREATE SEQUENCE POSTS_SEQ
START WITH 1 INCREMENT BY 1;

--테이블 조회
SELECT * FROM POSTS;

SELECT NVL(COUNT(POST_SEQ), 0)
FROM POSTS
WHERE BOARD_SEQ = 2
AND STATUS != '삭제'

SELECT 
			BBS_REF as bbsRef, 
			BBS_REPLY as bbsReply, 
			BBS_SEQ as bbsSeq, 
			USER_ID as userId, 
			BBS_TITLE as bbsTitle, 
			BBS_CONTENT as bbsContent, 
			BBS_READCOUNT as bbsReadCount, 
			BBS_STORED_FILENAME as bbsStoredFileName, 
			BBS_ORG_FILENAME as bbsOrgFileName, 
			BBS_STATUS as bbsStatus, 
			BBS_WDATE as bbsWdate
		FROM (
				SELECT BBS_REF, BBS_REPLY, BBS_SEQ, USER_ID, BBS_TITLE, BBS_CONTENT, BBS_READCOUNT, BBS_STORED_FILENAME, BBS_ORG_FILENAME, BBS_STATUS, BBS_WDATE, 
				ROW_NUMBER() OVER (ORDER BY BBS_REF desc, BBS_REPLY ASC) R
				FROM MAIN_BBS
				WHERE BOARD_NAME = '대문공지'
				AND BBS_STATUS = 1
		)
		WHERE R BETWEEN #{startArticle} and #{endArticle}
		
--더미데이터 넣기
INSERT INTO MAIN_BBS(
	BOARD_NAME, BBS_REF, BBS_SEQ, USER_ID, BBS_TITLE, 
	BBS_CONTENT, BBS_STORED_FILENAME, BBS_ORG_FILENAME
)
VALUES(
	#{boardName}, MAIN_BBS_SEQ.NEXTVAL, MAIN_BBS_SEQ.NEXTVAL, #{userId}, #{bbsTitle}, 
	#{bbsContent}, #{bbsStoredFileName}, #{bbsOrgFileName}
)

--테이블 이름 바꾸기
ALTER TABLE POSTS RENAME TO BOARDS_TO_POSTS;
ALTER TABLE MAIN_BBS RENAME TO POSTS;
