SELECT U.USER_ID, U.USER_NAME, U.USER_EMAIL, U.USER_PHONE, U.USER_ADDRESS, U.USER_AUTH, U.USER_STATUS, U.USER_BIRTH,
				S.STUDENT_REGIDATE, S.STUDENT_TERM, S.STUDENT_YEAR, S.STUDENT_TOTAL_CREDIT, S.STUDENT_TERM_GRADE, S.STUDENT_TOTAL_GRADE, S.STUDENT_MAJOR, S.STUDENT_FIRST_MAJOR
		FROM USERS U, STUDENT S
		WHERE U.USER_ID = S.STUDENT_ID
		AND U.USER_ID='학생1' AND U.USER_PW='학생1'

SELECT * FROM PROFESSOR;

UPDATE PROFESSOR
SET prof_major = '100'
WHERE prof_major IS NULL;

--데이터 조회용
SELECT SB.SUB_SEQ       , 
		   SB.SUB_CATEGORY  , 
		   SB.MAJOR_NUMBER  , 
		   SB.SUB_SEMESTER  , 
	       SB.SUB_NAME      , 
	       SB.PROFESSOR_ID  , 
	       SB.PROFESSOR_NAME, 
	       SB.SUB_INFO      , 
	       A.STUDENT_ID     , 
	       ST.STUDENT_NAME  , 
	       ST.STUDENT_YEAR  , 
	       A.PROFESSOR_GRADE
	  FROM SUBJECT SB, STUDENT ST, ASSESSMENT A
 	 WHERE SB.SUB_SEQ = A.SUB_SEQ_NUM
	   AND A.STUDENT_ID = '20170101'
	   AND A.STUDENT_ID = ST.STUDENT_ID
	   AND ST.STUDENT_YEAR = '1'
	   AND SB.SUB_SEMESTER = '1'
  	   AND A.PROFESSOR_GRADE = 0