--학생/교수/관리자 통합 계정 정보 테이블
CREATE TABLE USERS(
    USER_ID VARCHAR2(50) PRIMARY KEY,               --SYSDATE(2017)+MAJOR_NUMBER(100)+USER_SEQ(1,2,3...)
    USER_PW VARCHAR2(50) NOT NULL,
    USER_NAME VARCHAR2(50)  NOT NULL,
    USER_EMAIL VARCHAR2(50) NOT NULL,
    USER_PHONE VARCHAR2(50) NOT NULL,
    USER_ADDRESS VARCHAR2(255) NOT NULL,
    USER_AUTH NUMBER DEFAULT 100 NOT NULL,          --학생:100,교수:200,관리자:300
    MAJOR_NUMBER NUMBER DEFAULT 0 NOT NULL,         --없음:0,기계공학과:100,전기공학과:200,컴퓨터공학과:300...
    USER_STATUS NUMBER DEFAULT 100 NOT NULL         --재학:100,휴학:200,졸업:300제적:400
);

-- USER_ID 생성용 시퀀스
CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1; 

-- 조회용
SELECT * FROM USERS;
SELECT * FROM STUDENT;

SELECT *
FROM SUBJECT s, ASSESSMENT a
WHERE s.sub_seq = a.SUB_SEQ_NUM(+)

and MAJOR_NUMBER= '100' and a.student_id = 'jiyuns'
ORDER BY SUB_REF ASC, SUB_MAX_STUDENT DESC;

--데이터 삭제
DELETE FROM USERS;

--더미데이터 넣기
INSERT INTO USERS(
USER_ID, USER_PW, USER_NAME, USER_EMAIL, USER_PHONE, USER_ADDRESS, USER_AUTH,  USER_STATUS, USER_BIRTH, USER_PHOTO
)
VALUES(
'root', 'secret', '운영자', 'admin@admin.com', '000-0000-0000', '없음', 300, 0, 100, ''
)